#!/usr/bin/env python3
"""
regenerate_assets.py — 从 game-core/assets/ 原始资产文件重新生成
src/assets/generated/ 下的 C++ 文件，供 CCS 等非 CMake 构建系统使用。

用法:
  cd software/game-core
  python3 tools/regenerate_assets.py

CMake 构建不需要此脚本——CMake 会在构建时自动调用 asset_convert.py / audio2tone.py。
"""

import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GAME_CORE_ROOT = os.path.dirname(SCRIPT_DIR)
ASSETS_DIR = os.path.join(GAME_CORE_ROOT, "assets")
GEN_DIR = os.path.join(GAME_CORE_ROOT, "src", "assets", "generated")

ASSET_CONVERTER = os.path.join(SCRIPT_DIR, "asset_convert.py")
SOUND_CONVERTER = os.path.join(SCRIPT_DIR, "audio2tone.py")

# ── 资产注册表 ────────────────────────────────────────────────
# 格式: (名称, ID, 相对 assets/ 的路径)
ASSETS = [
    ("TEST_RED_SPRITE", 1, "sprites/test_red.raw"),
]

# 格式: (名称, 相对 assets/ 的路径)
SOUNDS = [
    ("BOOT",             "sounds/boot.tone"),
    ("BGM_MENU",         "sounds/bgm_menu.tone"),
    ("BGM_GUIDE",        "sounds/bgm_guide.tone"),
    ("BGM_PLAYGROUND",   "sounds/bgm_playground.tone"),
    ("BGM_SNAKE",        "sounds/bgm_snake.tone"),
    ("BGM_PACMAN",       "sounds/bgm_pacman.tone"),
    ("BGM_BREAKOUT",     "sounds/bgm_breakout.tone"),
    ("BGM_INVADERS",     "sounds/bgm_invaders.tone"),
    ("SFX_SELECT",       "sounds/sfx_select.tone"),
    ("SFX_CONFIRM",      "sounds/sfx_confirm.tone"),
    ("SFX_EAT",          "sounds/sfx_eat.tone"),
    ("SFX_DEATH_SNAKE",  "sounds/sfx_death_snake.tone"),
    ("SFX_CHOMP",        "sounds/sfx_chomp.tone"),
    ("SFX_DEATH_PACMAN", "sounds/sfx_death_pacman.tone"),
    ("SFX_POWER_PELLET", "sounds/sfx_power_pellet.tone"),
    ("SFX_BRICK",        "sounds/sfx_brick.tone"),
    ("SFX_PADDLE",       "sounds/sfx_paddle.tone"),
    ("SFX_DEATH_BREAKOUT", "sounds/sfx_death_breakout.tone"),
    ("SFX_SHOOT",        "sounds/sfx_shoot.tone"),
    ("SFX_EXPLOSION",    "sounds/sfx_explosion.tone"),
    ("SFX_UFO",          "sounds/sfx_ufo.tone"),
]


def run(cmd):
    print(f"  {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def main():
    os.makedirs(GEN_DIR, exist_ok=True)

    # ── 生成每个资产的 .cpp ──────────────────────────────────
    for name, asset_id, rel_path in ASSETS:
        src = os.path.join(ASSETS_DIR, rel_path)
        dst = os.path.join(GEN_DIR, f"{name}.cpp")
        var = f"_asset_{name}"
        if not os.path.exists(src):
            print(f"Warning: asset file not found: {src}", file=sys.stderr)
            continue
        run([sys.executable, ASSET_CONVERTER, src, dst, var])

    # ── 生成每个音效的 .cpp ──────────────────────────────────
    for name, rel_path in SOUNDS:
        src = os.path.join(ASSETS_DIR, rel_path)
        dst = os.path.join(GEN_DIR, f"{name}.cpp")
        var = f"_sound_{name}"
        if not os.path.exists(src):
            print(f"Warning: sound file not found: {src}", file=sys.stderr)
            continue
        run([sys.executable, SOUND_CONVERTER, src, dst, var])

    # ── 生成 AssetId.h ───────────────────────────────────────
    id_path = os.path.join(GEN_DIR, "AssetId.h")
    lines = [
        "// Auto-generated by regenerate_assets.py. Do not edit.",
        "#ifndef GEN_ASSET_ID_H",
        "#define GEN_ASSET_ID_H",
        "",
        "#include <cstdint>",
        "",
        "namespace handheld {",
        "namespace asset {",
        "",
    ]
    for name, asset_id, _ in ASSETS:
        lines.append(f"constexpr uint16_t {name} = {asset_id};")
    lines += [
        "",
        "}  // namespace asset",
        "}  // namespace handheld",
        "",
        "#endif  // GEN_ASSET_ID_H",
    ]
    with open(id_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Generated {id_path}")

    # ── 生成 asset_registry.cpp ──────────────────────────────
    reg_path = os.path.join(GEN_DIR, "asset_registry.cpp")
    lines = [
        "// Auto-generated by regenerate_assets.py. Do not edit.",
        '#include "core/assets/AssetEntry.h"',
        '#include "AssetId.h"',
        "",
    ]
    for name, _, _ in ASSETS:
        lines.append(f'extern "C" const unsigned char _asset_{name}[];')
        lines.append(f'extern "C" const unsigned int _asset_{name}_len;')
        lines.append("")
    lines.append('extern "C" const handheld::AssetEntry builtin_assets[] = {')
    for name, _, _ in ASSETS:
        lines.append(f'\t{{ handheld::asset::{name}, _asset_{name}, _asset_{name}_len }},')
    lines.append("};")
    lines.append(f'extern "C" const uint32_t builtin_assets_count = {len(ASSETS)};')
    lines.append("")
    with open(reg_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Generated {reg_path}")

    print(f"\nDone. {len(ASSETS)} asset(s), {len(SOUNDS)} sound(s) → {GEN_DIR}")


if __name__ == "__main__":
    main()
