# AssetHelpers.cmake
#
# add_assets() — 注册二进制资产文件，自动生成 C++ 代码并加入目标。
# add_sounds() — 将 .tone 音效文件转为 C++ Tone 数组并加入目标。
#
# 此文件位于 game-core/cmake/ 中，通过 CMAKE_CURRENT_LIST_DIR 定位转换脚本，
# 不依赖外部 REPO_ROOT 变量。

# 在 include 时捕获本文件所在目录（函数内部 CMAKE_CURRENT_LIST_DIR 会反映调用者目录）
set(_ASSET_HELPERS_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(_ASSET_CONVERTER "${_ASSET_HELPERS_DIR}/../tools/asset_convert.py")
set(_SOUND_CONVERTER "${_ASSET_HELPERS_DIR}/../tools/audio2tone.py")

find_program(_PYTHON python3)
if(NOT _PYTHON)
	message(FATAL_ERROR "AssetHelpers: python3 not found")
endif()

# ── add_assets ──────────────────────────────────────────────────
function(add_assets)
	cmake_parse_arguments(AR "" "TARGET" "ASSETS" ${ARGN})

	if(NOT AR_TARGET)
		message(FATAL_ERROR "add_assets: TARGET is required")
	endif()

	if(NOT AR_ASSETS)
		message(WARNING "add_assets: ASSETS is empty, nothing to register")
		return()
	endif()

	set(GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/_assets")
	file(MAKE_DIRECTORY "${GEN_DIR}")

	# ── AssetId.h ────────────────────────────────────────────────
	set(ID_FILE "${GEN_DIR}/AssetId.h")
	file(WRITE "${ID_FILE}"
		"// Auto-generated by add_assets(). Do not edit.\n"
		"#ifndef GEN_ASSET_ID_H\n"
		"#define GEN_ASSET_ID_H\n"
		"\n"
		"#include <cstdint>\n"
		"\n"
		"namespace handheld {\n"
		"namespace asset {\n"
		"\n"
	)

	# ── asset_registry.cpp ──────────────────────────────────────
	set(REG_FILE "${GEN_DIR}/asset_registry.cpp")
	file(WRITE "${REG_FILE}"
		"// Auto-generated by add_assets(). Do not edit.\n"
		"#include \"core/assets/AssetEntry.h\"\n"
		"#include \"AssetId.h\"\n"
		"\n"
	)

	set(ALL_SOURCES "")
	set(COUNT 0)

	list(LENGTH AR_ASSETS ARG_COUNT)
	foreach(OFF RANGE 0 ${ARG_COUNT} 3)
		math(EXPR NEXT "${OFF} + 2")
		if(NEXT GREATER_EQUAL ${ARG_COUNT})
			break()
		endif()

		list(GET AR_ASSETS ${OFF} NAME)
		math(EXPR OFF1 "${OFF} + 1")
		list(GET AR_ASSETS ${OFF1} ASSET_ID)
		math(EXPR OFF2 "${OFF} + 2")
		list(GET AR_ASSETS ${OFF2} FILE_PATH)

		if(NOT EXISTS "${FILE_PATH}")
			message(FATAL_ERROR "add_assets: asset file not found: ${FILE_PATH}")
		endif()

		set(CPP_FILE "${GEN_DIR}/${NAME}.cpp")
		list(APPEND ALL_SOURCES "${CPP_FILE}")

		add_custom_command(
			OUTPUT "${CPP_FILE}"
			COMMAND "${_PYTHON}" "${_ASSET_CONVERTER}"
				"${FILE_PATH}" "${CPP_FILE}" "_asset_${NAME}"
			DEPENDS "${FILE_PATH}" "${_ASSET_CONVERTER}"
			COMMENT "Generating asset: ${NAME}"
			VERBATIM
		)

		file(APPEND "${ID_FILE}"
			"constexpr uint16_t ${NAME} = ${ASSET_ID};\n"
		)

		file(APPEND "${REG_FILE}"
			"extern \"C\" const unsigned char _asset_${NAME}[];\n"
			"extern \"C\" const unsigned int _asset_${NAME}_len;\n"
			"\n"
		)

		math(EXPR COUNT "${COUNT} + 1")
	endforeach()

	file(APPEND "${ID_FILE}"
		"\n}  // namespace asset\n"
		"}  // namespace handheld\n"
		"\n"
		"#endif  // GEN_ASSET_ID_H\n"
	)

	file(APPEND "${REG_FILE}"
		"extern \"C\" const handheld::AssetEntry builtin_assets[] = {\n"
	)

	foreach(OFF RANGE 0 ${ARG_COUNT} 3)
		math(EXPR NEXT "${OFF} + 2")
		if(NEXT GREATER_EQUAL ${ARG_COUNT})
			break()
		endif()
		list(GET AR_ASSETS ${OFF} NAME)
		file(APPEND "${REG_FILE}"
			"\t{ handheld::asset::${NAME}, _asset_${NAME}, _asset_${NAME}_len },\n"
		)
	endforeach()

	file(APPEND "${REG_FILE}"
		"};\n"
		"extern \"C\" const uint32_t builtin_assets_count = ${COUNT};\n"
	)

	list(APPEND ALL_SOURCES "${REG_FILE}")

	target_sources(${AR_TARGET} PRIVATE ${ALL_SOURCES})
	target_include_directories(${AR_TARGET} PRIVATE "${GEN_DIR}")
endfunction()

# ── add_sounds ──────────────────────────────────────────────────
function(add_sounds)
	cmake_parse_arguments(AR "" "TARGET" "SOUNDS" ${ARGN})
	if(NOT AR_TARGET)
		message(FATAL_ERROR "add_sounds: TARGET is required")
	endif()
	if(NOT AR_SOUNDS)
		return()
	endif()

	set(GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/_sounds")
	file(MAKE_DIRECTORY "${GEN_DIR}")

	list(LENGTH AR_SOUNDS SND_LEN)
	foreach(OFF RANGE 0 ${SND_LEN} 2)
		math(EXPR NEXT "${OFF} + 1")
		if(NEXT GREATER_EQUAL ${SND_LEN})
			break()
		endif()
		list(GET AR_SOUNDS ${OFF} NAME)
		list(GET AR_SOUNDS ${NEXT} FILE_PATH)
		if(NOT EXISTS "${FILE_PATH}")
			message(FATAL_ERROR "add_sounds: file not found: ${FILE_PATH}")
		endif()
		set(CPP_FILE "${GEN_DIR}/${NAME}.cpp")
		add_custom_command(
			OUTPUT "${CPP_FILE}"
			COMMAND "${_PYTHON}" "${_SOUND_CONVERTER}"
				"${FILE_PATH}" "${CPP_FILE}" "_sound_${NAME}"
			DEPENDS "${FILE_PATH}" "${_SOUND_CONVERTER}"
			COMMENT "Generating sound: ${NAME}"
			VERBATIM
		)
		target_sources(${AR_TARGET} PRIVATE "${CPP_FILE}")
	endforeach()
endfunction()
