# AssetHelpers.cmake
#
# add_assets() — 注册二进制资产文件，自动生成 C++ 代码并加入目标。
#
# 用法:
#   set(REPO_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../..")
#   include(${REPO_ROOT}/cmake/AssetHelpers.cmake)
#
#   add_assets(TARGET <target>
#       ASSETS
#           <NAME>  <ID>  <路径>
#           ...
#   )
#
# 效果:
#   1. 将每个资产文件用 tools/asset_convert.py 转为 alignas(4) 的 .cpp
#   2. 生成 ${GEN_DIR}/AssetId.h — constexpr uint16_t 常量
#   3. 生成 ${GEN_DIR}/asset_registry.cpp — AssetEntry 数组
#   4. 上述生成文件通过 target_sources 加入 <target>

function(add_assets)
	cmake_parse_arguments(AR "" "TARGET" "ASSETS" ${ARGN})

	if(NOT AR_TARGET)
		message(FATAL_ERROR "add_assets: TARGET is required")
	endif()

	if(NOT AR_ASSETS)
		message(WARNING "add_assets: ASSETS is empty, nothing to register")
		return()
	endif()

	if(NOT REPO_ROOT)
		message(FATAL_ERROR "add_assets: REPO_ROOT must be set before calling")
	endif()

	set(GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/_assets")
	file(MAKE_DIRECTORY "${GEN_DIR}")
	set(CONVERTER "${REPO_ROOT}/tools/asset_convert.py")

	find_program(_PYTHON python3)
	if(NOT _PYTHON)
		message(FATAL_ERROR "add_assets: python3 not found")
	endif()

	# ── AssetId.h ────────────────────────────────────────────────
	set(ID_FILE "${GEN_DIR}/AssetId.h")
	file(WRITE "${ID_FILE}"
		"// Auto-generated by add_assets(). Do not edit.\n"
		"#ifndef GEN_ASSET_ID_H\n"
		"#define GEN_ASSET_ID_H\n"
		"\n"
		"#include <cstdint>\n"
		"\n"
		"namespace handheld {\n"
		"namespace asset {\n"
		"\n"
	)

	# ── asset_registry.cpp ──────────────────────────────────────
	set(REG_FILE "${GEN_DIR}/asset_registry.cpp")
	file(WRITE "${REG_FILE}"
		"// Auto-generated by add_assets(). Do not edit.\n"
		"#include \"core/assets/AssetEntry.h\"\n"
		"#include \"AssetId.h\"\n"
		"\n"
	)

	set(ALL_SOURCES "")
	set(COUNT 0)

	# 遍历 ASSETS 三元组 (NAME ID FILE_PATH)
	list(LENGTH AR_ASSETS ARG_COUNT)
	foreach(OFF RANGE 0 ${ARG_COUNT} 3)
		math(EXPR NEXT "${OFF} + 2")
		if(NEXT GREATER_EQUAL ${ARG_COUNT})
			break()
		endif()

		list(GET AR_ASSETS ${OFF} NAME)
		math(EXPR OFF1 "${OFF} + 1")
		list(GET AR_ASSETS ${OFF1} ASSET_ID)
		math(EXPR OFF2 "${OFF} + 2")
		list(GET AR_ASSETS ${OFF2} FILE_PATH)

		if(NOT EXISTS "${FILE_PATH}")
			message(FATAL_ERROR "add_assets: asset file not found: ${FILE_PATH}")
		endif()

		set(CPP_FILE "${GEN_DIR}/${NAME}.cpp")
		list(APPEND ALL_SOURCES "${CPP_FILE}")

		add_custom_command(
			OUTPUT "${CPP_FILE}"
			COMMAND "${_PYTHON}" "${CONVERTER}"
				"${FILE_PATH}" "${CPP_FILE}" "_asset_${NAME}"
			DEPENDS "${FILE_PATH}" "${CONVERTER}"
			COMMENT "Generating asset: ${NAME}"
			VERBATIM
		)

		# AssetId.h: constexpr uint16_t NAME = ID;
		file(APPEND "${ID_FILE}"
			"constexpr uint16_t ${NAME} = ${ASSET_ID};\n"
		)

		# registry: extern decls
		file(APPEND "${REG_FILE}"
			"extern \"C\" const unsigned char _asset_${NAME}[];\n"
			"extern \"C\" const unsigned int _asset_${NAME}_len;\n"
			"\n"
		)

		math(EXPR COUNT "${COUNT} + 1")
	endforeach()

	# 闭合 AssetId.h
	file(APPEND "${ID_FILE}"
		"\n}  // namespace asset\n"
		"}  // namespace handheld\n"
		"\n"
		"#endif  // GEN_ASSET_ID_H\n"
	)

	# 闭合 registry.cpp
	file(APPEND "${REG_FILE}"
		"extern \"C\" const handheld::AssetEntry builtin_assets[] = {\n"
	)

	# 重新遍历追加 entries（需要再遍历一次 APPEND）
	foreach(OFF RANGE 0 ${ARG_COUNT} 3)
		math(EXPR NEXT "${OFF} + 2")
		if(NEXT GREATER_EQUAL ${ARG_COUNT})
			break()
		endif()
		list(GET AR_ASSETS ${OFF} NAME)
		file(APPEND "${REG_FILE}"
			"\t{ handheld::asset::${NAME}, _asset_${NAME}, _asset_${NAME}_len },\n"
		)
	endforeach()

	file(APPEND "${REG_FILE}"
		"};\n"
		"extern \"C\" const uint32_t builtin_assets_count = ${COUNT};\n"
	)

	list(APPEND ALL_SOURCES "${REG_FILE}")

	target_sources(${AR_TARGET} PRIVATE ${ALL_SOURCES})
	target_include_directories(${AR_TARGET} PRIVATE "${GEN_DIR}")
endfunction()

# add_sounds() — 将 .tone 音效文件转为 C++ Tone 数组并加入目标。
#
# 用法:
#   add_sounds(TARGET <target>
#       SOUNDS
#           <NAME>  <路径>
#           ...
#   )
function(add_sounds)
	cmake_parse_arguments(AR "" "TARGET" "SOUNDS" ${ARGN})
	if(NOT AR_TARGET)
		message(FATAL_ERROR "add_sounds: TARGET is required")
	endif()
	if(NOT REPO_ROOT)
		message(FATAL_ERROR "add_sounds: REPO_ROOT must be set")
	endif()
	if(NOT AR_SOUNDS)
		return()
	endif()

	set(GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/_sounds")
	file(MAKE_DIRECTORY "${GEN_DIR}")
	set(CONVERTER "${REPO_ROOT}/tools/audio2tone.py")
	find_program(_PYTHON python3)
	if(NOT _PYTHON)
		message(FATAL_ERROR "add_sounds: python3 not found")
	endif()

	list(LENGTH AR_SOUNDS SND_LEN)
	foreach(OFF RANGE 0 ${SND_LEN} 2)
		math(EXPR NEXT "${OFF} + 1")
		if(NEXT GREATER_EQUAL ${SND_LEN})
			break()
		endif()
		list(GET AR_SOUNDS ${OFF} NAME)
		list(GET AR_SOUNDS ${NEXT} FILE_PATH)
		if(NOT EXISTS "${FILE_PATH}")
			message(FATAL_ERROR "add_sounds: file not found: ${FILE_PATH}")
		endif()
		set(CPP_FILE "${GEN_DIR}/${NAME}.cpp")
		add_custom_command(
			OUTPUT "${CPP_FILE}"
			COMMAND "${_PYTHON}" "${CONVERTER}"
				"${FILE_PATH}" "${CPP_FILE}" "_sound_${NAME}"
			DEPENDS "${FILE_PATH}" "${CONVERTER}"
			COMMENT "Generating sound: ${NAME}"
			VERBATIM
		)
		target_sources(${AR_TARGET} PRIVATE "${CPP_FILE}")
	endforeach()
endfunction()
